"""
This type stub file was generated by pyright.
"""

class Timer:
    def __init__(self, timeout, callback) -> None:
        ...
    
    def cancel(self): # -> None:
        ...
    


def debounce(wait): # -> Callable[..., Callable[..., None]]:
    ...

