"""
This type stub file was generated by pyright.
"""

from functools import total_ordering
from .base import PydeckType

@total_ordering
class Function(PydeckType):
    """Indicate a function type with arguments and set already in pydeck

    Parameters
    ----------

    name : str
        Function name
    **kwargs
        arguments and value of each argument to be storing the function information
    """
    __KEY = ...
    def __init__(self, name: str, **kwargs) -> None:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def serialize(self): # -> dict[str, str]:
        ...
    


