"""
This type stub file was generated by pyright.
"""

from pydeck.types.base import PydeckType

valid_url_regex = ...
valid_image_regex = ...
def get_encoding(path: str) -> str:
    ...

class Image(PydeckType):
    """Indicate an image for pydeck

    Parameters
    ----------

    path : str
        Path to image (either remote or local)
    """
    def __init__(self, path: str) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    @staticmethod
    def validate(path): # -> bool:
        ...
    


