"""
This type stub file was generated by pyright.
"""

from functools import total_ordering
from .base import PydeckType

@total_ordering
class String(PydeckType):
    """Indicate a string value in pydeck

    Parameters
    ----------

    value : str
        Value of the string
    """
    def __init__(self, s: str, quote_type: str = ...) -> None:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


