"""
This type stub file was generated by pyright.
"""

from enum import Enum

class BaseMapProvider(Enum):
    """Basemap provider available in pydeck"""
    MAPBOX = ...
    GOOGLE_MAPS = ...
    CARTO = ...


