"""
This type stub file was generated by pyright.
"""

"""
Support serializing objects into JSON
"""
IGNORE_KEYS = ...
def to_camel_case(snake_case): # -> LiteralString | Literal['']:
    """Makes a snake case string into a camel case one

    Parameters
    -----------
    snake_case : str
        Snake-cased string (e.g., "snake_cased") to be converted to camel-case (e.g., "camelCase")

    Returns
    -------
    str
        Camel-cased (e.g., "camelCased") version of input string
    """
    ...

def lower_first_letter(s): # -> Literal['']:
    ...

def camel_and_lower(w): # -> LiteralString | Literal['']:
    ...

def lower_camel_case_keys(attrs): # -> None:
    """Makes all the keys in a dictionary camel-cased and lower-case

    Parameters
    ----------
    attrs : dict
        Dictionary for which all the keys should be converted to camel-case
    """
    ...

def default_serialize(o, remap_function=...): # -> str | dict[Any, Any]:
    """Default method for rendering JSON from a dictionary"""
    ...

def serialize(serializable): # -> str:
    """Takes a serializable object and JSONifies it"""
    ...

class JSONMixin:
    def __repr__(self): # -> str:
        """
        Override of string representation method to return a JSON-ified version of the
        Deck object.
        """
        ...
    
    def to_json(self): # -> str:
        """
        Return a JSON-ified version of the Deck object.
        """
        ...
    


