"""
This type stub file was generated by pyright.
"""

from .json_tools import JSONMixin

class LightSettings(JSONMixin):
    """
    Configuration of lights on the plane

    Parameters
    ---------
        lights_position : array, default None
            Location of lights in an array of X/Y/Z coordinates
        diffuse_ratio : float, default None
            Proportion of light at many angles
        specular_ratio : float, default None
            Proportion of light reflected in a mirror-like manner
        lights_strength : array, default None
            Brightness of lights
        number_of_lights : int, default None
            Number of lights in visualization
    """
    def __init__(self, number_of_lights=..., lights_position=..., diffuse_ratio=..., specular_ratio=..., lights_strength=..., ambient_ratio=...) -> None:
        ...
    


