"""
This type stub file was generated by pyright.
"""

from .json_tools import JSONMixin

TYPE_IDENTIFIER = ...
class View(JSONMixin):
    """
    Represents a "hard configuration" of a camera location

    Parameters
    ---------
    type : str, default None
        deck.gl view to display, e.g., MapView
    controller : bool, default None
        If enabled, camera becomes interactive.
    **kwargs
        Any of the parameters passable to a deck.gl View
    """
    def __init__(self, type=..., controller=..., width=..., height=..., **kwargs) -> None:
        ...
    
    @property
    def type(self): # -> Any:
        ...
    
    @type.setter
    def type(self, type_name): # -> None:
        ...
    


