"""
This type stub file was generated by pyright.
"""

def array_to_binary(ar, obj=..., force_contiguous=...): # -> dict[str, Any] | None:
    ...

def serialize_columns(data_set_cols, obj=...): # -> defaultdict[Any, dict[Any, Any]] | None:
    ...

data_buffer_serialization = ...
