"""
This type stub file was generated by pyright.
"""

def get_random_rgb(): # -> list[int]:
    """Generate a random RGB value

    Returns
    -------
    list of float
        Random RGB array
    """
    ...

def assign_random_colors(data_vector): # -> OrderedDict[str, Any]:
    """Produces lookup table keyed by each class of data, with value as an RGB array

    Parameters
    ---------
    data_vector : list
        Vector of data classes to be categorized, passed from the data itself

    Returns
    -------
    collections.OrderedDict
        Dictionary of random RGBA value per class, keyed on class
    """
    ...

