"""
This type stub file was generated by pyright.
"""

def is_pandas_df(obj):
    """Check if an object is a Pandas DataFrame

    Returns
    -------
    bool
        Returns True if object is a Pandas DataFrame and False otherwise
    """
    ...

def has_geo_interface(obj): # -> bool:
    ...

def records_from_geo_interface(data): # -> list[Any]:
    """Un-nest data from object implementing __geo_interface__ standard"""
    ...

