"""
This type stub file was generated by pyright.
"""

settings = ...
class Settings:
    """Global settings for pydeck

    Parameters
    ----------
    custom_libraries : list
        List of dictionaries of the format {'libraryName': 'LibraryName', 'resouceUri': 'deck.gl class URL'}.
        For example, if there was a custom deck.gl Layer classed `TagmapLayer`
        bundled for distribution at the path `https://demourl.libpath/bundle.js`,
        one could load it into pydeck by doing the following:

        ```
        pydeck.settings.custom_libraries = [
            {
                'libraryName': 'tagmapLibrary',
                'resourceUri': 'https://demourl.libpath/bundle.js'
            }
        ]
        layer = pydeck.Layer(
            'TagmapLayer',  # Assumes that tagmapLibrary exports TagmapLayer
            # <... kwargs here ...>
        )
        ```
    configuration : str
    default_layer_attributes : dict
    """
    def __init__(self, custom_libraries: list = ..., configuration: str = ..., default_layer_attributes: dict = ...) -> None:
        ...
    
    def register_library(self, name, uri): # -> None:
        ...
    


if not settings:
    settings = ...
